import UIKit
final class ManHinhCaiDat:UIViewController {
    private let vao = UIDatePicker(),ra = UIDatePicker(),nghi = UITextField(),phut = UITextField(),mucTieu = UITextField()
    override func viewDidLoad(){super.viewDidLoad();title = "Cài đặt";view.backgroundColor = .systemGroupedBackground;navigationItem.rightBarButtonItem = UIBarButtonItem(title:"Lưu",style:.done,target:self,action:#selector(luu));let c = KhoDuLieu.dungChung.caiDat
        [vao,ra].forEach{$0.datePickerMode = .time;$0.preferredDatePickerStyle = .compact};vao.date = TienIchNgay.taoGio(ngay:Date(),gio:c.gioBatDau,phut:c.phutBatDau);ra.date = TienIchNgay.taoGio(ngay:Date(),gio:c.gioKetThuc,phut:c.phutKetThuc)
        [(nghi,"\(c.nghiPhut)"),(phut,String(format:"%.0f",c.phutChuan)),(mucTieu,String(format:"%.2f",c.mucTieuThang))].forEach{$0.0.borderStyle = .roundedRect;$0.0.keyboardType = .decimalPad;$0.0.text = $0.1}
        let s = UIStackView(arrangedSubviews:[hang("Giờ vào mặc định",vao),hang("Giờ về mặc định",ra),hang("Phút nghỉ mặc định",nghi),hang("Phút chuẩn mặc định",phut),hang("Mục tiêu tháng (%)",mucTieu)]);s.axis = .vertical;s.spacing = 18;s.translatesAutoresizingMaskIntoConstraints = false;view.addSubview(s);NSLayoutConstraint.activate([s.topAnchor.constraint(equalTo:view.safeAreaLayoutGuide.topAnchor,constant:24),s.leadingAnchor.constraint(equalTo:view.leadingAnchor,constant:18),s.trailingAnchor.constraint(equalTo:view.trailingAnchor,constant:-18)])
    }
    private func hang(_ t:String,_ v:UIView)->UIStackView{let l = UILabel();l.text = t;l.font = .systemFont(ofSize:16,weight:.semibold);let h = UIStackView(arrangedSubviews:[l,v]);h.distribution = .equalSpacing;h.alignment = .center;return h}
    @objc private func luu(){let cal = TienIchNgay.lich,a = cal.dateComponents([.hour,.minute],from:vao.date),b = cal.dateComponents([.hour,.minute],from:ra.date);let x = CaiDat(gioBatDau:a.hour!,phutBatDau:a.minute!,gioKetThuc:b.hour!,phutKetThuc:b.minute!,nghiPhut:Int(nghi.text ?? "") ?? 60,phutChuan:Double(phut.text?.replacingOccurrences(of:",",with:".") ?? "") ?? 720,mucTieuThang:Double(mucTieu.text?.replacingOccurrences(of:",",with:".") ?? "") ?? 100);KhoDuLieu.dungChung.luuCaiDat(x);navigationController?.popViewController(animated:true)}
}
